package com.example.saulovera.proximatedemo.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.saulovera.proximatedemo.dao.ProfileEntity;
import com.example.saulovera.proximatedemo.dao.SectionEntity;

import com.example.saulovera.proximatedemo.dao.ProfileEntityDao;
import com.example.saulovera.proximatedemo.dao.SectionEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig profileEntityDaoConfig;
    private final DaoConfig sectionEntityDaoConfig;

    private final ProfileEntityDao profileEntityDao;
    private final SectionEntityDao sectionEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        profileEntityDaoConfig = daoConfigMap.get(ProfileEntityDao.class).clone();
        profileEntityDaoConfig.initIdentityScope(type);

        sectionEntityDaoConfig = daoConfigMap.get(SectionEntityDao.class).clone();
        sectionEntityDaoConfig.initIdentityScope(type);

        profileEntityDao = new ProfileEntityDao(profileEntityDaoConfig, this);
        sectionEntityDao = new SectionEntityDao(sectionEntityDaoConfig, this);

        registerDao(ProfileEntity.class, profileEntityDao);
        registerDao(SectionEntity.class, sectionEntityDao);
    }
    
    public void clear() {
        profileEntityDaoConfig.getIdentityScope().clear();
        sectionEntityDaoConfig.getIdentityScope().clear();
    }

    public ProfileEntityDao getProfileEntityDao() {
        return profileEntityDao;
    }

    public SectionEntityDao getSectionEntityDao() {
        return sectionEntityDao;
    }

}
