package com.example.saulovera.proximatedemo.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PROFILE_ENTITY".
 */
public class ProfileEntity {

    private Long id;
    /** Not-null value. */
    private String name;
    private String lastname;
    private String secondname;
    private String telephone;
    private String zipCode;
    private Double latPoint;
    private Double lonPoint;

    public ProfileEntity() {
    }

    public ProfileEntity(Long id) {
        this.id = id;
    }

    public ProfileEntity(Long id, String name, String lastname, String secondname, String telephone, String zipCode, Double latPoint, Double lonPoint) {
        this.id = id;
        this.name = name;
        this.lastname = lastname;
        this.secondname = secondname;
        this.telephone = telephone;
        this.zipCode = zipCode;
        this.latPoint = latPoint;
        this.lonPoint = lonPoint;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getSecondname() {
        return secondname;
    }

    public void setSecondname(String secondname) {
        this.secondname = secondname;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getZipCode() {
        return zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public Double getLatPoint() {
        return latPoint;
    }

    public void setLatPoint(Double latPoint) {
        this.latPoint = latPoint;
    }

    public Double getLonPoint() {
        return lonPoint;
    }

    public void setLonPoint(Double lonPoint) {
        this.lonPoint = lonPoint;
    }

}
