package com.example.saulovera.proximatedemo.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.saulovera.proximatedemo.dao.SectionEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SECTION_ENTITY".
*/
public class SectionEntityDao extends AbstractDao<SectionEntity, Long> {

    public static final String TABLENAME = "SECTION_ENTITY";

    /**
     * Properties of entity SectionEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Id_server = new Property(1, String.class, "id_server", false, "ID_SERVER");
        public final static Property Seccion = new Property(2, String.class, "seccion", false, "SECCION");
        public final static Property Abrev = new Property(3, String.class, "abrev", false, "ABREV");
    };


    public SectionEntityDao(DaoConfig config) {
        super(config);
    }
    
    public SectionEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SECTION_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ID_SERVER\" TEXT NOT NULL ," + // 1: id_server
                "\"SECCION\" TEXT NOT NULL ," + // 2: seccion
                "\"ABREV\" TEXT);"); // 3: abrev
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SECTION_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SectionEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getId_server());
        stmt.bindString(3, entity.getSeccion());
 
        String abrev = entity.getAbrev();
        if (abrev != null) {
            stmt.bindString(4, abrev);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SectionEntity readEntity(Cursor cursor, int offset) {
        SectionEntity entity = new SectionEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // id_server
            cursor.getString(offset + 2), // seccion
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // abrev
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SectionEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId_server(cursor.getString(offset + 1));
        entity.setSeccion(cursor.getString(offset + 2));
        entity.setAbrev(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SectionEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SectionEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
