package com.example.saulovera.proximatedemo.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SECTION_ENTITY".
 */
public class SectionEntity {

    private Long id;
    /** Not-null value. */
    private String id_server;
    /** Not-null value. */
    private String seccion;
    private String abrev;

    public SectionEntity() {
    }

    public SectionEntity(Long id) {
        this.id = id;
    }

    public SectionEntity(Long id, String id_server, String seccion, String abrev) {
        this.id = id;
        this.id_server = id_server;
        this.seccion = seccion;
        this.abrev = abrev;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getId_server() {
        return id_server;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId_server(String id_server) {
        this.id_server = id_server;
    }

    /** Not-null value. */
    public String getSeccion() {
        return seccion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSeccion(String seccion) {
        this.seccion = seccion;
    }

    public String getAbrev() {
        return abrev;
    }

    public void setAbrev(String abrev) {
        this.abrev = abrev;
    }

}
